In [94]:
import os
import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn import linear_model, metrics, cross_validation, feature_selection

pd.set_option('display.max_rows', 10)
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 10)

%matplotlib inline
plt.style.use('ggplot')

#pd.set_option('display.max_rows', 10)
#pd.set_option('display.notebook_repr_html', True)
#pd.set_option('display.max_columns', 10)

In [2]:
df = pd.read_csv(os.path.join('..', 'CODE', '2016-FCC-New-Coders-Survey-Data.csv'))

/Users/Miranda/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (21,57) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [26]:
df

Age  AttendedBootcamp  BootcampFinish  BootcampFullJobAfter  \
0      28.0               0.0             NaN                   NaN   
1      22.0               0.0             NaN                   NaN   
2      19.0               0.0             NaN                   NaN   
3      26.0               0.0             NaN                   NaN   
4      20.0               0.0             NaN                   NaN   
...     ...               ...             ...                   ...   
15615  39.0               0.0             NaN                   NaN   
15616  27.0               0.0             NaN                   NaN   
15617  37.0               0.0             NaN                   NaN   
15618  26.0               0.0             NaN                   NaN   
15619  22.0               0.0             NaN                   NaN   

       BootcampLoanYesNo       ...        ResourceW3Schools ResourceYouTube  \
0                    NaN       ...                      NaN             NaN   
1                    NaN       ...                      NaN             NaN   
2                    NaN       ...                      NaN             NaN   
3                    NaN       ...                      NaN             NaN   
4                    NaN       ...                      NaN             NaN   
...                  ...       ...                      ...             ...   
15615                NaN       ...                      NaN             NaN   
15616                NaN       ...                      NaN             NaN   
15617                NaN       ...                      NaN             NaN   
15618                NaN       ...                      NaN             NaN   
15619                NaN       ...                      NaN             NaN   

                                  SchoolDegree              SchoolMajor  \
0               some college credit, no degree                      NaN   
1               some college credit, no degree                      NaN   
2      high school diploma or equivalent (GED)                      NaN   
3                            bachelor's degree  Cinematography And Film   
4               some college credit, no degree                      NaN   
...                                        ...                      ...   
15615                        bachelor's degree                Chemistry   
15616                        bachelor's degree   Electrical Engineering   
15617                        bachelor's degree                Chemistry   
15618       master's degree (non-professional)                     Math   
15619                        bachelor's degree           Graphic Design   

       StudentDebtOwe  
0             20000.0  
1                 NaN  
2                 NaN  
3              7000.0  
4                 NaN  
...               ...  
15615             NaN  
15616             NaN  
15617             NaN  
15618             NaN  
15619         40000.0  

[15620 rows x 113 columns]

In [27]:
df.columns

Index([u'Age', u'AttendedBootcamp', u'BootcampFinish', u'BootcampFullJobAfter',
       u'BootcampLoanYesNo', u'BootcampMonthsAgo', u'BootcampName',
       u'BootcampPostSalary', u'BootcampRecommend', u'ChildrenNumber',
       ...
       u'ResourceSoloLearn', u'ResourceStackOverflow', u'ResourceTreehouse',
       u'ResourceUdacity', u'ResourceUdemy', u'ResourceW3Schools',
       u'ResourceYouTube', u'SchoolDegree', u'SchoolMajor', u'StudentDebtOwe'],
      dtype='object', length=113)

In [28]:
df.corr()

Age  AttendedBootcamp  BootcampFinish  \
Age                   1.000000          0.052738        0.100825   
AttendedBootcamp      0.052738          1.000000             NaN   
BootcampFinish        0.100825               NaN        1.000000   
BootcampFullJobAfter -0.276556               NaN             NaN   
BootcampLoanYesNo    -0.010962               NaN        0.040286   
...                        ...               ...             ...   
ResourceUdacity            NaN               NaN             NaN   
ResourceUdemy              NaN               NaN             NaN   
ResourceW3Schools          NaN               NaN             NaN   
ResourceYouTube            NaN               NaN             NaN   
StudentDebtOwe        0.118368         -0.012080        0.006506   

                      BootcampFullJobAfter  BootcampLoanYesNo       ...        \
Age                              -0.276556          -0.010962       ...         
AttendedBootcamp                       NaN                NaN       ...         
BootcampFinish                         NaN           0.040286       ...         
BootcampFullJobAfter              1.000000          -0.001930       ...         
BootcampLoanYesNo                -0.001930           1.000000       ...         
...                                    ...                ...       ...         
ResourceUdacity                        NaN                NaN       ...         
ResourceUdemy                          NaN                NaN       ...         
ResourceW3Schools                      NaN                NaN       ...         
ResourceYouTube                        NaN                NaN       ...         
StudentDebtOwe                    0.051056          -0.085362       ...         

                      ResourceUdacity  ResourceUdemy  ResourceW3Schools  \
Age                               NaN            NaN                NaN   
AttendedBootcamp                  NaN            NaN                NaN   
BootcampFinish                    NaN            NaN                NaN   
BootcampFullJobAfter              NaN            NaN                NaN   
BootcampLoanYesNo                 NaN            NaN                NaN   
...                               ...            ...                ...   
ResourceUdacity                   NaN            NaN                NaN   
ResourceUdemy                     NaN            NaN                NaN   
ResourceW3Schools                 NaN            NaN                NaN   
ResourceYouTube                   NaN            NaN                NaN   
StudentDebtOwe                    NaN            NaN                NaN   

                      ResourceYouTube  StudentDebtOwe  
Age                               NaN        0.118368  
AttendedBootcamp                  NaN       -0.012080  
BootcampFinish                    NaN        0.006506  
BootcampFullJobAfter              NaN        0.051056  
BootcampLoanYesNo                 NaN       -0.085362  
...                               ...             ...  
ResourceUdacity                   NaN             NaN  
ResourceUdemy                     NaN             NaN  
ResourceW3Schools                 NaN             NaN  
ResourceYouTube                   NaN             NaN  
StudentDebtOwe                    NaN        1.000000  

[85 rows x 85 columns]

In [6]:
df.BootcampName.unique()

array([nan, 'Codify Academy', 'DaVinci Coders', 'Coder Foundry',
       'General Assembly', 'Thinkful', 'Flatiron School', 'DevMountain',
       'The Iron Yard', 'Codeup', 'Code Fellows', 'Bloc.io',
       'The Firehose Project', 'Prime Digital Academy',
       'Free Code Camp is not a bootcamp - please scroll up and change answer to "no"',
       'Galvanize', 'Ada', 'Skillcrush', 'Hack Reactor', 'Coding House',
       'Software Guild', 'BrainStation', 'Fullstack Academy',
       'Makers Academy', 'Turing', 'Lighthouse Labs', 'MakerSquare',
       'Wyncode', 'Dev Bootcamp', 'Bit Bootcamp', 'Coder Camps',
       'IronHack', 'Epicodus', 'Tech Talent South', 'Coding Dojo',
       'PDX Code Guild', 'Hackbright Academy', 'CareerFoundry',
       'LearningFuze', 'Zip Code Wilmington', 'Launch Academy',
       'LAMP Camp', 'Nashville Software School', 'RefactorU',
       'CodeCore Bootcamp', 'Sabio.la', 'Grand Circus', 'App Academy',
       'Devschool', 'Learn.Modern-Developer', 'Grace Hopper 

In [80]:
model = smf.ols(formula = 'BootcampFullJobAfter ~ AttendedBootcamp ', data = df).fit()
model.summary()


#NEED TO TURN INTO BINARY VARIABLES

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                             
================================================================================
Dep. Variable:     BootcampFullJobAfter   R-squared:                       0.000
Model:                              OLS   Adj. R-squared:                  0.000
Method:                   Least Squares   F-statistic:                       inf
Date:                  Tue, 14 Jun 2016   Prob (F-statistic):                nan
Time:                          18:15:28   Log-Likelihood:                -451.73
No. Observations:                   635   AIC:                             905.5
Df Residuals:                       634   BIC:                             909.9
Df Model:                             0                                         
Covariance Type:              nonrobust                                         
====================================================================================
                       coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------------
Intercept            0.2921      0.010     29.849      0.000         0.273     0.311
AttendedBootcamp     0.2921      0.010     29.849      0.000         0.273     0.311
==============================================================================
Omnibus:                       12.001   Durbin-Watson:                   1.861
Prob(Omnibus):                  0.002   Jarque-Bera (JB):              106.195
Skew:                          -0.342   Prob(JB):                     8.71e-24
Kurtosis:                       1.117   Cond. No.                          inf
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

## Look at 'Age'

In [83]:
len(df.Age.dropna())

13613

In [85]:
len(df.Age.isnull())

15620

In [86]:
len(df.Age)

15620

## Look at 'AttendedBootcamp'

In [62]:
df.AttendedBootcamp.unique()

array([  0.,  nan,   1.])

In [63]:
df.AttendedBootcamp.value_counts()

0.0    14427
1.0      953
Name: AttendedBootcamp, dtype: int64

In [68]:
df.AttendedBootcamp.count()

15380

## Look at 'Bootcamp Finish'

In [41]:
df.BootcampFinish.unique()

array([ nan,   1.,   0.])

In [59]:
df.BootcampFinish.value_counts()

1.0    643
0.0    290
Name: BootcampFinish, dtype: int64

In [60]:
len(df.BootcampFinish.dropna())

933

## Look at 'BootcampFullJobAfter'

In [35]:
df.BootcampFullJobAfter.unique()

array([ nan,   0.,   1.])

In [17]:
df.BootcampFullJobAfter.value_counts()

1.0    371
0.0    264
Name: BootcampFullJobAfter, dtype: int64

In [58]:
len(df.BootcampFullJobAfter.dropna())

635

In [20]:
df.corr().BootcampFullJobAfter

Age                    -0.276556
AttendedBootcamp             NaN
BootcampFinish               NaN
BootcampFullJobAfter    1.000000
BootcampLoanYesNo      -0.001930
                          ...   
ResourceUdacity              NaN
ResourceUdemy                NaN
ResourceW3Schools            NaN
ResourceYouTube              NaN
StudentDebtOwe          0.051056
Name: BootcampFullJobAfter, dtype: float64

## Look at 'ExpectedEarning'

In [71]:
len(df.ExpectedEarning.dropna())

6077

## Look at 'BootcampPostSalary'

In [76]:
len(df.BootcampPostSalary.dropna())

330

## Look at 'IsSoftwareDev'

In [78]:
df.IsSoftwareDev.value_counts()

0.0    11234
1.0     4303
Name: IsSoftwareDev, dtype: int64

## Look at 'MonthsProgramming'

In [79]:
df.MonthsProgramming.value_counts()

12.0     1549
6.0      1345
1.0      1253
3.0      1190
2.0      1119
         ... 
145.0       1
146.0       1
148.0       1
157.0       1
340.0       1
Name: MonthsProgramming, dtype: int64

# Linear Modeling with `sklearn`  

*from codealong 7*

Look At:
    - Age 
    - AttendedBootcamp (y/n)
    - BootcampFinish (y/n)
    - BootcampFullJobAfter (y/n)
    - ExpectedEarning
    - BootcampPostSalary
    - IsSoftwareDev
    - MonthsProgramming

In [87]:
subset_df = df.dropna(axis = 'index', subset = ['Age', 'AttendedBootcamp', 'ExpectedEarning', 'BootcampFinish', 'BootcampFullJobAfter', 'ExpectedEarning', 'BootcampPostSalary', 'IsSoftwareDev', 'MonthsProgramming'])

In [95]:
def linear_modeling_with_sklearn(X, y):
    model = linear_model.LinearRegression(fit_intercept = True)
    model.fit(X, y)

    print 'F-statistic (performed for each regressor independently)'
    print '- F-value', feature_selection.f_regression(X, y)[0]
    print '- p-value', feature_selection.f_regression(X, y)[1]
    print 'R^2 =', model.score(X, y)
    print 'Coefficients'
    print '- beta_0 (intercept) =', model.intercept_
    print '- beta_n (n > 0)     =', model.coef_

### BootcampPostSalary ~ Age with `statsmodels`

In [90]:
smf.ols(formula = 'BootcampPostSalary ~ Age', data = subset_df).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     BootcampPostSalary   R-squared:                       0.176
Model:                            OLS   Adj. R-squared:                  0.101
Method:                 Least Squares   F-statistic:                     2.345
Date:                Tue, 14 Jun 2016   Prob (F-statistic):              0.154
Time:                        18:26:05   Log-Likelihood:                -153.66
No. Observations:                  13   AIC:                             311.3
Df Residuals:                      11   BIC:                             312.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept   1.186e+05   4.04e+04      2.935      0.014      2.97e+04  2.08e+05
Age        -1785.1071   1165.682     -1.531      0.154     -4350.755   780.541
==============================================================================
Omnibus:                        6.699   Durbin-Watson:                   2.471
Prob(Omnibus):                  0.035   Jarque-Bera (JB):                3.471
Skew:                           1.218   Prob(JB):                        0.176
Kurtosis:                       3.689   Cond. No.                         141.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### BootcampPostSalary ~ Age with `sklearn` (Simple Linear Modeling)

In [97]:
X = subset_df[ ['Age'] ]
y = subset_df.BootcampPostSalary

linear_modeling_with_sklearn(X, y)

F-statistic (performed for each regressor independently)
- F-value [ 2.34513854]
- p-value [ 0.15391303]
R^2 = 0.17572980126
Coefficients
- beta_0 (intercept) = 118622.445643
- beta_n (n > 0)     = [-1785.10707863]


### BootcampPostSalary ~ Age + MonthsProgramming with `statsmodels`

In [98]:
smf.ols(formula = 'BootcampPostSalary ~ Age + MonthsProgramming', data = subset_df).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     BootcampPostSalary   R-squared:                       0.319
Model:                            OLS   Adj. R-squared:                  0.183
Method:                 Least Squares   F-statistic:                     2.341
Date:                Tue, 14 Jun 2016   Prob (F-statistic):              0.147
Time:                        18:29:03   Log-Likelihood:                -152.42
No. Observations:                  13   AIC:                             310.8
Df Residuals:                      10   BIC:                             312.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [95.0% Conf. Int.]
-------------------------------------------------------------------------------------
Intercept          1.223e+05   3.86e+04      3.168      0.010      3.63e+04  2.08e+05
Age               -1475.2106   1131.748     -1.303      0.222     -3996.901  1046.480
MonthsProgramming  -686.0792    473.290     -1.450      0.178     -1740.636   368.477
==============================================================================
Omnibus:                        5.524   Durbin-Watson:                   2.965
Prob(Omnibus):                  0.063   Jarque-Bera (JB):                2.752
Skew:                           1.097   Prob(JB):                        0.253
Kurtosis:                       3.518   Cond. No.                         172.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [33]:
#model = smf.ols(formula = 'BootcampFullJobAfter ~ AttendedBootcamp + age + gender + age * gender', data = df).fit()
#model.summary()


#'gpm ~ weight + age + horsepower_sqrt + age * horsepower_sqrt', data = df).fit()

In [31]:
#code the bootcamps people went to into #S

### BootcampPostSalary ~ Age + MonthsProgramming with `sklearn` (Multiple Linear Modeling)

In [99]:
X = subset_df[ ['Age', 'MonthsProgramming'] ]
y = subset_df.BootcampPostSalary

linear_modeling_with_sklearn(X, y)

F-statistic (performed for each regressor independently)
- F-value [ 2.34513854  2.80400347]
- p-value [ 0.15391303  0.12219244]
R^2 = 0.318859605907
Coefficients
- beta_0 (intercept) = 122348.94268
- beta_n (n > 0)     = [-1475.21057566  -686.07922862]
